# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - verabeleza

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://unhas.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_749a2c2d06174ae195215e575cfea4bb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ff01e0d335794ce99ffe8d700b5de4ba }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: unhas.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_749a2c2d06174ae195215e575cfea4bb }}/flashsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'verabeleza'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_858dd2cf9ebd4667be25b145d2af702e }}
        images: 'unhas.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_749a2c2d06174ae195215e575cfea4bb }}/flashsite:${{ github.sha }}'